

module CalaisOntology
  CALAIS_ENTITIES = %w(
    Anniversary
    City
    Company
    Continent
    Country
    Currency
    EmailAddress
    EntertainmentAwardEvent
    Facility
    FaxNumber
    Holiday
    IndustryTerm
    MarketIndex
    MedicalCondition
    MedicalTreatment
    Movie
    MusicAlbum
    MusicGroup
    NaturalFeature
    OperatingSystem
    Organization
    Person
    PhoneNumber
    PoliticalEvent
    Product
    ProgrammingLanguage
    ProvinceOrState
    PublishedMedium
    RadioProgram
    RadioStation
    Region
    SportsEvent
    SportsGame
    SportsLeague
    TVShow
    TVStation
    Technology
    URL
  )

CALAIS_EVENTS = %w(
    Acquisition
    Alliance
    AnalystEarningsEstimate
    AnalystRecommendation
    ArmedAttack
    ArmsPurchaseSale
    Arrest
    Bankruptcy
    BonusSharesIssuance
    BusinessRelation
    Buybacks
    CandidatePosition
    CompanyAccountingChange
    CompanyAffiliates
    CompanyCompetitor
    CompanyCustomer
    CompanyEarningsAnnouncement
    CompanyEarningsGuidance
    CompanyEmployeesNumber
    CompanyExpansion
    CompanyForceMajeure
    CompanyFounded
    CompanyInvestment
    CompanyLaborIssues
    CompanyLayoffs
    CompanyLegalIssues
    CompanyLocation
    CompanyListingChange
    CompanyMeeting
    CompanyNameChange
    CompanyProduct
    CompanyReorganization
    CompanyRestatement
    CompanyTechnology
    CompanyUsingProduct
    CompanyTicker
    ConferenceCall
    Conviction
    CreditRating
    DebtFinancing
    DelayedFiling
    DiplomaticRelations
    Dividend
    EmploymentChange
    EmploymentRelation
    EnvironmentalIssue
    EquityFinancing
    Extinction
    FamilyRelation
    FDAPhase
    Indictment
    IndicesChanges
    IPO
    JointVenture
    ManMadeDisaster
    Merger
    MilitaryAction
    MovieRelease
    MusicAlbumRelease
    NaturalDisaster
    PatentFiling
    PatentIssuance
    PersonAttributes
    PersonCareer
    PersonCommunication
    PersonEducation
    PersonEmailAddress
    PersonLocation
    PersonParty
    PersonRelation
    PersonTravel
    PoliticalEndorsement
    PoliticalRelationship
    PollsResult
    ProductIssues
    ProductRecall
    ProductRelease
    Quotation
    SecondaryIssuance
    StockSplit
    Trial
    VotingResult
)



CALAIS_TOPICS = %w(
    Business_Finance
    Disaster_Accident
    Education
    Entertainment_Culture
    Environment
    Health_Medical_Pharma
    Hospitality_Recreation
    Human_Interest
    Labor
    Law_Crime
    Politics
    Religion_Belief
    Social_Issues
    Sports
    Technology_Internet
    Weather
    War_Conflict
    Other
)

end

